### PR TITLE
Address the centering emergency.

### PR DESCRIPTION
**Pull request by MilesMcBain**

### CODE REVIEW

**Comment by MilesMcBain** [comment]
Maybe the background choice could use more thought.

**Comment by MilesMcBain** [comment]
CSS tweaks play nicely with author attribution.

**Comment by njtierney** [comment]
I'm not sure if `svg` is a better image format, but my initial thoughts were that it would be smaller than png and render better.

**Comment by njtierney** [comment]
Also, I'm pretty sure that the CSS changes should fix most of the centering/resizing problems.

**Comment by MilesMcBain** [comment]
Closing.

**Pull request closed without merging**
